In [10]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
import sys

python_list = list(range(100))
python_list[:4]

[0, 1, 2, 3]

In [9]:
sys.getsizeof(python_list[0])

28

In [10]:
sys.getsizeof(python_list[0])*len(python_list)

2800

In [12]:
numpy_array = np.arange(100)
numpy_array[:4]

array([0, 1, 2, 3])

In [13]:
numpy_array.nbytes

400

In [18]:
import time

SIZE = 1000000
l1 = list(range(SIZE))
l2 = list(range(SIZE))
start_time = time.time()
l3 = [x + y for x,y in zip(l1,l2)]
end_time = time.time()
print("Python list took: ",end_time - start_time)

Python list took:  0.1372973918914795


In [19]:
n1 = np.arange(SIZE)
n2 = np.arange(SIZE)
n1[:3],n2[:3]

(array([0, 1, 2]), array([0, 1, 2]))

In [20]:
start_time = time.time()
n3 = n1+n2
end_time = time.time()
print("Numpy array took: ", end_time-start_time)

Numpy array took:  0.00855565071105957


In [1]:
l1 = list(range(5))
l2 = list(range(5))
l1[:3],l2[:3]

([0, 1, 2], [0, 1, 2])

In [2]:
l1 + l2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [5]:
l3 = [x+y for x,y in zip(l1,l2)]
l3

[0, 2, 4, 6, 8]

In [8]:
list(zip(l1,l2))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

In [11]:
n1 = np.arange(5)
n2 = np.arange(5)
n1,n2

(array([0, 1, 2, 3, 4]), array([0, 1, 2, 3, 4]))

In [12]:
n3 = n1 + n2
n3

array([0, 2, 4, 6, 8])

In [13]:
n3 = n1*n2
n3

array([ 0,  1,  4,  9, 16])

In [14]:
rev_q1 = np.array([10,12,9])
rev_q1

array([10, 12,  9])

In [15]:
rev_q1.ndim

1

In [17]:
rev = np.array([[10,12,9],[15,11,13]])
rev.ndim


2

In [18]:
rev[1,0]

15

In [19]:
rev[1][0]

15

In [20]:
rev[1,0] = 14
rev

array([[10, 12,  9],
       [14, 11, 13]])

In [21]:
rev.dtype

dtype('int32')

In [22]:
rev.itemsize

4

In [23]:
rev = np.array([[10,12,9],[15,11,13]],dtype = np.float64)
rev.itemsize

8

In [24]:
rev.dtype

dtype('float64')

In [25]:
rev.size

6

In [26]:
rev.shape

(2, 3)

In [28]:
np.sort(rev,axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [29]:
np.sort(rev)

array([[ 9., 10., 12.],
       [11., 13., 15.]])

In [30]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
np.arange(3)

array([0, 1, 2])

In [33]:
np.arange(20,30)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [34]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [35]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [36]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [37]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [38]:
rev.ravel()

array([10., 12.,  9., 15., 11., 13.])

In [41]:
rev.reshape((3,2))

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [42]:
rev.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [43]:
rev.min()

9.0

In [44]:
rev.max()

15.0

In [45]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [ ]:
rev.sum(axis=0) # columnwise operation bhayo

array([25., 23., 22.])

In [47]:
rev.sum(axis=1)

array([31., 39.])

In [48]:
for row in rev:
    print("Row: ",row)

Row:  [10. 12.  9.]
Row:  [15. 11. 13.]


In [49]:
b = np.array([1,4,16])
np.sqrt(b)

array([1., 2., 4.])

In [50]:
np.square(b)

array([  1,  16, 256])

In [51]:
np.std(b)

6.48074069840786

In [52]:
q1 = np.array([
    [200, 220, 250],  # Product A
    [150, 180, 210],  # Product B
    [300, 330, 360] 
])

q2 = np.array([
    [209, 231, 259],  # Product A
    [155, 192, 222],  # Product B
    [310, 340, 375]   # Product C
])

In [53]:
q1+q2

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [54]:
q2 - q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [55]:
(q2 - q1)*100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [56]:
prices = np.array([
    [10, 12, 11],  # Prices for Product A in different regions
    [8,  9,  10],  # Prices for Product B
    [15, 16, 17]   # Prices for Product C
])
q1_rev = q1*prices

In [57]:
q1_rev

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [61]:
q1_discounts = q1_rev*0.02
q1_discounts

array([[ 40. ,  52.8,  55. ],
       [ 24. ,  32.4,  42. ],
       [ 90. , 105.6, 122.4]])

In [59]:
net_revenue = q1_rev - q1_discounts
net_revenue

array([[1960. , 2587.2, 2695. ],
       [1176. , 1587.6, 2058. ],
       [4410. , 5174.4, 5997.6]])

In [60]:
np.sum(q1_discounts)

564.2

In [62]:
features = np.array([
    [2000, 3], # house 1
    [1800, 2]  # house 2
])
weights = np.array([150, 50000])
price = np.dot(features,weights)
price

array([450000, 370000])

In [63]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.cross(c,d)

array([-3,  6, -3])